### PR TITLE
Add zbar, tests, maintainers

### LINKED ISSUE #1: Add zbar dependency?
It looks like the [zbar](https://github.com/conda-forge/zbar-feedstock) library should be a dependency... it may also be worth adding an `output` with `pillow` and testing some of the scripts, etc.

### PR DESCRIPTION
**Pull request by bollwyvl**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Notes:
- [x] fixes #1
  - > note: this is not presently available for windows 
- [x] adds python pins
- [x] adds `pip check`
- [x] adds `entry_point`
- [x] adds `nosetests` with `98` coverage threshold (needed images from upstream)
- [x] cleans up some metadata
- [x] adds self as maintainer :wave:

### CODE REVIEW

**Comment by mrakitin** [comment]
By any chance, can this PR be merged soon? I also noticed the `pyzbar` package is missing the `zbar` dependency. Thanks!

**Comment by bollwyvl** [comment]
:bell: @conda-forge/zbar

**Comment by bollwyvl** [comment]
@mrakitin are you interested in co-maintaining?

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by mrakitin** [comment]
> @mrakitin are you interested in co-maintaining?

Sure! Thanks for the offer. I've been maintaining our version of both packages in https://github.com/nsls-ii-forge/zbar-feedstock/blob/master/recipe/meta.yaml and https://github.com/nsls-ii-forge/pyzbar-feedstock/blob/master/recipe/meta.yaml, so happy to do it in conda-forge.

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by bollwyvl** [comment]
thanks!

**Comment by bollwyvl** [comment]
@mrakitin a shiny penny to you if you figure out win builds!

**Comment by mrakitin** [comment]
Thanks, @bollwyvl!

**Pull request merged**
